@Library ("tikal-advanced-pipeline") _

properties([parameters([string(name: 'FLOW', defaultValue: 'feature-CI')])])

def settings = new TAP_basic_flow_settings()
settings.flow=env.FLOW
settings.gitUrl ="git@github.com:tikalk/tikal-advanced-pipeline.git"

TAP_basicPipeline (settings)
