@Library ("tikal-advanced-pipeline") _

properties([parameters([string(name: 'FLOW', defaultValue: 'feature-CI')])])

def set = new tap-basic_flow_settings()
set.flow=env.FLOW
set.gitUrl ="git@github.com:tikalk/tikal-advanced-pipeline.git"

tap-basicPipeline set
