node
{
    stage('Code commit')
    {
        echo "Code commit"
    }
    stage('Code build')
    {
        echo "Code build"
    }
    stage('Unit tests')
    {
        echo "Unit tests"
    }
    stage('Deploy')
    {
        echo "Deploy"
    }
    stage('Integration tests')
    {
        echo "Integration tests"
    }
}
