pipeline
{
    agent any
    stages
    {
        stage('Code commit')
        {
            steps
            {
                echo "Code commit"
            }
        }
        stage('Code build')
        {
            steps
            {
                echo "Code build"
            }
        }
        stage('Unit tests')
        {
            steps
            {
                echo "Unit tests"
            }
        }
        stage('Deploy')
        {
            steps
            {
                echo "Deploy"
            }
        }
        stage('Integration tests')
        {
            steps
            {
                echo "Integration tests"
            }
        }
    }
}
