node
{
    stage('Setup')
    {
        currentBuild.displayName = "#${BUILD_ID} | ${SEQUENCE}"
        checkout([$class           : 'GitSCM', branches: [[name: 'master']],
                  userRemoteConfigs: [[url
                                       : 'https://github.com/tikalk/maven-hello-world']]
        ])
    }
    stage('Code build')
    {
        withMaven(jdk: 'jdk8u131', maven: 'mvn350')
        {
            sh "mvn clean install -DskipTests -f my-app/pom.xml"
        }
    }
    stage('Unit tests')
    {
        withMaven(jdk: 'jdk8u131', maven: 'mvn350')
                {
                    sh "mvn test -f my-app/pom.xml"
                }
    }
    stage('Integration tests')
    {
        sh "java -jar my-app/target/my-app-1.0-SNAPSHOT.jar ${SEQUENCE}"
    }
    stage('JUnit report')
    {
        junit 'my-app/target//surefire-reports/*.xml'
    }
    stage('Archive artifacts')
    {
        archiveArtifacts '**/target/**/my-app-*.jar'
    }
}
